# Generated by Django 4.1.7 on 2023-03-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=14)),
                ('attack', models.IntegerField(default=8)),
                ('defense', models.IntegerField(default=8)),
                ('luck', models.IntegerField(default=7)),
                ('magic', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyCharacter',
            fields=[
                ('characters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.characters')),
                ('description', models.TextField()),
            ],
            bases=('characters.characters',),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('characters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.characters')),
                ('backpack', models.ManyToManyField(to='characters.item')),
            ],
            bases=('characters.characters',),
        ),
    ]
